### PR TITLE
release/2.0.1

### LINKED ISSUE #106: java.lang.IllegalStateException upon ending billing connection.
### Problem faced on a Android device - Vivo 1818

Hi @hyochan once again!

Today,  I got a crash report from my play console the stack trace is shown below.

```
java.lang.IllegalStateException: 
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:35)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error (MethodChannel.java:14)
  at com.dooboolab.flutterinapppurchase.AndroidInappPurchasePlugin$1.onBillingServiceDisconnected (AndroidInappPurchasePlugin.java:10)
  at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection.onServiceDisconnected (BillingClientImpl.java:28)
  at android.app.LoadedApk$ServiceDispatcher.doDeath (LoadedApk.java:1789)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1804)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7157)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:537)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:876)
```

My guess is that, this might have occured when the plugin called upon end connection of billing services.

Is this stacktrace of any help for making the plugin more stable.
Thanks in advance!

### PR DESCRIPTION
**Pull request by hyochan**
- Resolve #106

### CODE REVIEW

File: lib/flutter_inapp_purchase.dart [hunk 1]
```diff
@@ -599,6 +601,10 @@ class FlutterInappPurchase {
           Map<String, dynamic> result = jsonDecode(call.arguments);
           _purchaseErrorController.add(new PurchaseResult.fromJSON(result));
           break;
+        case "connected":
+          Map<String, dynamic> result = call.arguments;
+          _purchaseErrorController.add(new PurchaseResult.fromJSON(result));
```
Comment (xPutnikx) [inline lib/flutter_inapp_purchase.dart]: Looks like you used wrong stream here.

File: lib/flutter_inapp_purchase.dart [hunk 2]
```diff
@@ -27,6 +27,9 @@ class FlutterInappPurchase {
   static StreamController<PurchaseResult> _purchaseErrorController;
   static Stream<PurchaseResult> get purchaseError => _purchaseErrorController.stream;
 
+  static StreamController<PurchaseResult> _connectionController;
```
Comment (xPutnikx) [inline lib/flutter_inapp_purchase.dart]: I think stream type should be different here, mb Boolean
